CNT='^#include <string.h>'
grep "${CNT}" ./core/arch/arch.c
grep "${CNT}" ./core/arch/arch_exports.h
grep "${CNT}" ./core/arch/emit_utils_shared.c
grep "${CNT}" ./core/arch/instr_shared.c
grep "${CNT}" ./core/arch/interp.c
grep "${CNT}" ./core/arch/opnd_shared.c
grep "${CNT}" ./core/arch/retcheck.c
grep "${CNT}" ./core/arch/x86/decode.c
grep "${CNT}" ./core/arch/x86/emit_utils.c
grep "${CNT}" ./core/arch/x86/encode.c
grep "${CNT}" ./core/arch/x86/mangle.c
grep "${CNT}" ./core/arch/x86/x86.asm
grep "${CNT}" ./core/arch/x86/x86_asm_defines.asm
grep "${CNT}" ./core/config.c
grep "${CNT}" ./core/emit.c
grep "${CNT}" ./core/fcache.c
grep "${CNT}" ./core/fragment.c
grep "${CNT}" ./core/hashtablex.h
grep "${CNT}" ./core/heap.c
grep "${CNT}" ./core/hotpatch.c
grep "${CNT}" ./core/io.c
grep "${CNT}" ./core/jit_opt.c
grep "${CNT}" ./core/lib/instrument.c
grep "${CNT}" ./core/monitor.c
grep "${CNT}" ./core/perscache.c
grep "${CNT}" ./core/string.c
grep "${CNT}" ./core/synch.c
grep "${CNT}" ./core/translate.c
grep "${CNT}" ./core/unix/loader_linux.c
grep "${CNT}" ./core/unix/module.c
grep "${CNT}" ./core/unix/module_elf.c
grep "${CNT}" ./core/unix/native_elf.c
grep "${CNT}" ./core/unix/os.c
grep "${CNT}" ./core/unix/signal.c
grep "${CNT}" ./core/unix/signal_linux_x86.c
grep "${CNT}" ./core/utils.c
grep "${CNT}" ./dynamorio_t.c 
