BLD_DIR="/home/sgx/project/sgx/sgx-dbi/drrun/debug"
DR_ROOT="/home/sgx/project/sgx/sgx-dbi/drrun"

CMAKE="/usr/bin/cmake"
PERL="/usr/bin/perl"
CPP="/usr/bin/cpp"
CC="/usr/bin/cc"
AS="/usr/bin/as"
#cd ${BLD_DIR} && ${CMAKE} -E cmake_depends "Unix Makefiles" ${DR_ROOT} ${DR_ROOT}/core ${BLD_DIR} ${BLD_DIR}/core ${BLD_DIR}/core/CMakeFiles/generate_syslog.dir/DependInfo.cmake --color=
#[  0%] Generating ../event_strings.h
#cd ${BLD_DIR}/core && ${PERL} ${DR_ROOT}/core/gen_event_strings.pl ${DR_ROOT}/core/win32/events.mc ${BLD_DIR}/event_strings.h
#[  0%] Built target generate_syslog
#cd ${BLD_DIR} && ${CMAKE} -E cmake_depends "Unix Makefiles" ${DR_ROOT} ${DR_ROOT}/core ${BLD_DIR} ${BLD_DIR}/core ${BLD_DIR}/core/CMakeFiles/drhelper.dir/DependInfo.cmake --color=
#[  0%] Building ASM object core/CMakeFiles/drhelper.dir/arch/asm_shared.asm.o
#cd ${BLD_DIR}/core && ${CPP}  -g   -fPIC -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations   -DCPP2ASM -E ${DR_ROOT}/core/arch/asm_shared.asm -o CMakeFiles/drhelper.dir/arch/asm_shared.asm.o.s
#cd ${BLD_DIR}/core && ${CMAKE} -Dfile=CMakeFiles/drhelper.dir/arch/asm_shared.asm.o.s -P "${DR_ROOT}/make/CMake_asm.cmake"
cd ${BLD_DIR}/core && ${AS}  -mmnemonic=intel -msyntax=intel -mnaked-reg --64 --noexecstack -g -o CMakeFiles/drhelper.dir/arch/asm_shared.asm.o CMakeFiles/drhelper.dir/arch/asm_shared.asm.o.s
#[  0%] Building ASM object core/CMakeFiles/drhelper.dir/arch/x86/x86_shared.asm.o
#cd ${BLD_DIR}/core && ${CPP}  -g   -fPIC -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations   -DCPP2ASM -E ${DR_ROOT}/core/arch/x86/x86_shared.asm -o CMakeFiles/drhelper.dir/arch/x86/x86_shared.asm.o.s
#cd ${BLD_DIR}/core && ${CMAKE} -Dfile=CMakeFiles/drhelper.dir/arch/x86/x86_shared.asm.o.s -P "${DR_ROOT}/make/CMake_asm.cmake"
cd ${BLD_DIR}/core && ${AS}  -mmnemonic=intel -msyntax=intel -mnaked-reg --64 --noexecstack -g -o CMakeFiles/drhelper.dir/arch/x86/x86_shared.asm.o CMakeFiles/drhelper.dir/arch/x86/x86_shared.asm.o.s
#[  0%] Building C object core/CMakeFiles/drhelper.dir/lib/dr_helper.c.o
cd ${BLD_DIR}/core && ${CC}   -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable     -fPIC -o CMakeFiles/drhelper.dir/lib/dr_helper.c.o   -c ${DR_ROOT}/core/lib/dr_helper.c
#[ 11%] Linking C static library ../lib64/libdrhelper.a
#cd ${BLD_DIR}/core && ${CMAKE} -P CMakeFiles/drhelper.dir/cmake_clean_target.cmake
cd ${BLD_DIR}/core && ${CMAKE} -E cmake_link_script CMakeFiles/drhelper.dir/link.txt --verbose=
#[ 11%] Built target drhelper
#cd ${BLD_DIR} && ${CMAKE} -E cmake_depends "Unix Makefiles" ${DR_ROOT} ${DR_ROOT}/core ${BLD_DIR} ${BLD_DIR}/core ${BLD_DIR}/core/CMakeFiles/drdecode.dir/DependInfo.cmake --color=
#[ 11%] Building C object core/CMakeFiles/drdecode.dir/arch/opnd_shared.c.o
cd ${BLD_DIR}/core && ${CC}   -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable     -DNOT_DYNAMORIO_CORE_PROPER -DSTANDALONE_DECODER -fPIC -o CMakeFiles/drdecode.dir/arch/opnd_shared.c.o   -c ${DR_ROOT}/core/arch/opnd_shared.c
#[ 11%] Building C object core/CMakeFiles/drdecode.dir/arch/x86/opnd.c.o
cd ${BLD_DIR}/core && ${CC}   -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable     -DNOT_DYNAMORIO_CORE_PROPER -DSTANDALONE_DECODER -fPIC -o CMakeFiles/drdecode.dir/arch/x86/opnd.c.o   -c ${DR_ROOT}/core/arch/x86/opnd.c
#[ 22%] Building C object core/CMakeFiles/drdecode.dir/arch/instr_shared.c.o
cd ${BLD_DIR}/core && ${CC}   -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable     -DNOT_DYNAMORIO_CORE_PROPER -DSTANDALONE_DECODER -fPIC -o CMakeFiles/drdecode.dir/arch/instr_shared.c.o   -c ${DR_ROOT}/core/arch/instr_shared.c
#[ 22%] Building C object core/CMakeFiles/drdecode.dir/arch/x86/instr.c.o
cd ${BLD_DIR}/core && ${CC}   -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable     -DNOT_DYNAMORIO_CORE_PROPER -DSTANDALONE_DECODER -fPIC -o CMakeFiles/drdecode.dir/arch/x86/instr.c.o   -c ${DR_ROOT}/core/arch/x86/instr.c
#[ 22%] Building C object core/CMakeFiles/drdecode.dir/arch/instrlist.c.o
cd ${BLD_DIR}/core && ${CC}   -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable     -DNOT_DYNAMORIO_CORE_PROPER -DSTANDALONE_DECODER -fPIC -o CMakeFiles/drdecode.dir/arch/instrlist.c.o   -c ${DR_ROOT}/core/arch/instrlist.c
#[ 22%] Building C object core/CMakeFiles/drdecode.dir/arch/decode_shared.c.o
cd ${BLD_DIR}/core && ${CC}   -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable     -DNOT_DYNAMORIO_CORE_PROPER -DSTANDALONE_DECODER -fPIC -o CMakeFiles/drdecode.dir/arch/decode_shared.c.o   -c ${DR_ROOT}/core/arch/decode_shared.c
#[ 22%] Building C object core/CMakeFiles/drdecode.dir/arch/x86/decode.c.o
cd ${BLD_DIR}/core && ${CC}   -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable     -DNOT_DYNAMORIO_CORE_PROPER -DSTANDALONE_DECODER -fPIC -o CMakeFiles/drdecode.dir/arch/x86/decode.c.o   -c ${DR_ROOT}/core/arch/x86/decode.c
#[ 33%] Building C object core/CMakeFiles/drdecode.dir/arch/encode_shared.c.o
cd ${BLD_DIR}/core && ${CC}   -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable     -DNOT_DYNAMORIO_CORE_PROPER -DSTANDALONE_DECODER -fPIC -o CMakeFiles/drdecode.dir/arch/encode_shared.c.o   -c ${DR_ROOT}/core/arch/encode_shared.c
#[ 33%] Building C object core/CMakeFiles/drdecode.dir/arch/x86/encode.c.o
cd ${BLD_DIR}/core && ${CC}   -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable     -DNOT_DYNAMORIO_CORE_PROPER -DSTANDALONE_DECODER -fPIC -o CMakeFiles/drdecode.dir/arch/x86/encode.c.o   -c ${DR_ROOT}/core/arch/x86/encode.c
#[ 33%] Building C object core/CMakeFiles/drdecode.dir/arch/disassemble_shared.c.o
cd ${BLD_DIR}/core && ${CC}   -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable     -DNOT_DYNAMORIO_CORE_PROPER -DSTANDALONE_DECODER -fPIC -o CMakeFiles/drdecode.dir/arch/disassemble_shared.c.o   -c ${DR_ROOT}/core/arch/disassemble_shared.c
#[ 33%] Building C object core/CMakeFiles/drdecode.dir/arch/x86/disassemble.c.o
cd ${BLD_DIR}/core && ${CC}   -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable     -DNOT_DYNAMORIO_CORE_PROPER -DSTANDALONE_DECODER -fPIC -o CMakeFiles/drdecode.dir/arch/x86/disassemble.c.o   -c ${DR_ROOT}/core/arch/x86/disassemble.c
#[ 44%] Building C object core/CMakeFiles/drdecode.dir/arch/x86/decode_table.c.o
cd ${BLD_DIR}/core && ${CC}   -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable     -DNOT_DYNAMORIO_CORE_PROPER -DSTANDALONE_DECODER -fPIC -o CMakeFiles/drdecode.dir/arch/x86/decode_table.c.o   -c ${DR_ROOT}/core/arch/x86/decode_table.c
#[ 44%] Building C object core/CMakeFiles/drdecode.dir/arch/x86/decode_fast.c.o
cd ${BLD_DIR}/core && ${CC}   -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable     -DNOT_DYNAMORIO_CORE_PROPER -DSTANDALONE_DECODER -fPIC -o CMakeFiles/drdecode.dir/arch/x86/decode_fast.c.o   -c ${DR_ROOT}/core/arch/x86/decode_fast.c
#[ 44%] Building C object core/CMakeFiles/drdecode.dir/arch/x86/mangle.c.o
cd ${BLD_DIR}/core && ${CC}   -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable     -DNOT_DYNAMORIO_CORE_PROPER -DSTANDALONE_DECODER -fPIC -o CMakeFiles/drdecode.dir/arch/x86/mangle.c.o   -c ${DR_ROOT}/core/arch/x86/mangle.c
#[ 44%] Building C object core/CMakeFiles/drdecode.dir/arch/decodelib.c.o
cd ${BLD_DIR}/core && ${CC}   -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable     -DNOT_DYNAMORIO_CORE_PROPER -DSTANDALONE_DECODER -fPIC -o CMakeFiles/drdecode.dir/arch/decodelib.c.o   -c ${DR_ROOT}/core/arch/decodelib.c
#[ 55%] Linking C static library ../lib64/libdrdecode.a
#cd ${BLD_DIR}/core && ${CMAKE} -P CMakeFiles/drdecode.dir/cmake_clean_target.cmake
cd ${BLD_DIR}/core && ${CMAKE} -E cmake_link_script CMakeFiles/drdecode.dir/link.txt --verbose=
#[ 55%] Built target drdecode
#cd ${BLD_DIR} && ${CMAKE} -E cmake_depends "Unix Makefiles" ${DR_ROOT} ${DR_ROOT}/core ${BLD_DIR} ${BLD_DIR}/core ${BLD_DIR}/core/CMakeFiles/drinjectlib.dir/DependInfo.cmake --color=
#[ 55%] Building C object core/CMakeFiles/drinjectlib.dir/unix/injector.c.o
cd ${BLD_DIR}/core && ${CC}   -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable     -DNOT_DYNAMORIO_CORE_PROPER -DRC_IS_DRINJECTLIB -o CMakeFiles/drinjectlib.dir/unix/injector.c.o   -c ${DR_ROOT}/core/unix/injector.c
#[ 66%] Building C object core/CMakeFiles/drinjectlib.dir/config.c.o
cd ${BLD_DIR}/core && ${CC}   -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable     -DNOT_DYNAMORIO_CORE_PROPER -DRC_IS_DRINJECTLIB -o CMakeFiles/drinjectlib.dir/config.c.o   -c ${DR_ROOT}/core/config.c
#[ 66%] Building C object core/CMakeFiles/drinjectlib.dir/unix/os.c.o
cd ${BLD_DIR}/core && ${CC}   -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable     -DNOT_DYNAMORIO_CORE_PROPER -DRC_IS_DRINJECTLIB -o CMakeFiles/drinjectlib.dir/unix/os.c.o   -c ${DR_ROOT}/core/unix/os.c
#[ 66%] Building C object core/CMakeFiles/drinjectlib.dir/string.c.o
cd ${BLD_DIR}/core && ${CC}   -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable     -DNOT_DYNAMORIO_CORE_PROPER -DRC_IS_DRINJECTLIB -o CMakeFiles/drinjectlib.dir/string.c.o   -c ${DR_ROOT}/core/string.c
#[ 66%] Building C object core/CMakeFiles/drinjectlib.dir/io.c.o
cd ${BLD_DIR}/core && ${CC}   -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable     -DNOT_DYNAMORIO_CORE_PROPER -DRC_IS_DRINJECTLIB -o CMakeFiles/drinjectlib.dir/io.c.o   -c ${DR_ROOT}/core/io.c
#[ 66%] Building C object core/CMakeFiles/drinjectlib.dir/unix/module_elf.c.o
cd ${BLD_DIR}/core && ${CC}   -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable     -DNOT_DYNAMORIO_CORE_PROPER -DRC_IS_DRINJECTLIB -o CMakeFiles/drinjectlib.dir/unix/module_elf.c.o   -c ${DR_ROOT}/core/unix/module_elf.c
#[ 77%] Linking C static library ../lib64/libdrinjectlib.a
#cd ${BLD_DIR}/core && ${CMAKE} -P CMakeFiles/drinjectlib.dir/cmake_clean_target.cmake
cd ${BLD_DIR}/core && ${CMAKE} -E cmake_link_script CMakeFiles/drinjectlib.dir/link.txt --verbose=
#[ 77%] Built target drinjectlib
#cd ${BLD_DIR} && ${CMAKE} -E cmake_depends "Unix Makefiles" ${DR_ROOT} ${DR_ROOT}/libutil ${BLD_DIR} ${BLD_DIR}/libutil ${BLD_DIR}/libutil/CMakeFiles/drfrontendlib.dir/DependInfo.cmake --color=
#[ 77%] Building C object libutil/CMakeFiles/drfrontendlib.dir/dr_frontend_unix.c.o
cd ${BLD_DIR}/libutil && ${CC}  -DNOT_DYNAMORIO_CORE_PROPER -I${DR_ROOT}/core/unix -I${BLD_DIR} -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/win32 -I${DR_ROOT}/core/lib -I${DR_ROOT}/core  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable     -o CMakeFiles/drfrontendlib.dir/dr_frontend_unix.c.o   -c ${DR_ROOT}/libutil/dr_frontend_unix.c
#[ 77%] Building C object libutil/CMakeFiles/drfrontendlib.dir/__/core/unix/os.c.o
cd ${BLD_DIR}/libutil && ${CC}  -DNOT_DYNAMORIO_CORE_PROPER -I${DR_ROOT}/core/unix -I${BLD_DIR} -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/win32 -I${DR_ROOT}/core/lib -I${DR_ROOT}/core  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable     -o CMakeFiles/drfrontendlib.dir/__/core/unix/os.c.o   -c ${DR_ROOT}/core/unix/os.c
#[ 77%] Building C object libutil/CMakeFiles/drfrontendlib.dir/__/core/unix/module_elf.c.o
cd ${BLD_DIR}/libutil && ${CC}  -DNOT_DYNAMORIO_CORE_PROPER -I${DR_ROOT}/core/unix -I${BLD_DIR} -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/win32 -I${DR_ROOT}/core/lib -I${DR_ROOT}/core  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable     -o CMakeFiles/drfrontendlib.dir/__/core/unix/module_elf.c.o   -c ${DR_ROOT}/core/unix/module_elf.c
#[ 77%] Building C object libutil/CMakeFiles/drfrontendlib.dir/dr_frontend_common.c.o
cd ${BLD_DIR}/libutil && ${CC}  -DNOT_DYNAMORIO_CORE_PROPER -I${DR_ROOT}/core/unix -I${BLD_DIR} -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/win32 -I${DR_ROOT}/core/lib -I${DR_ROOT}/core  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable     -o CMakeFiles/drfrontendlib.dir/dr_frontend_common.c.o   -c ${DR_ROOT}/libutil/dr_frontend_common.c
#[ 88%] Linking C static library ../lib64/libdrfrontendlib.a
#cd ${BLD_DIR}/libutil && ${CMAKE} -P CMakeFiles/drfrontendlib.dir/cmake_clean_target.cmake
cd ${BLD_DIR}/libutil && ${CMAKE} -E cmake_link_script CMakeFiles/drfrontendlib.dir/link.txt --verbose=
#[ 88%] Built target drfrontendlib
#cd ${BLD_DIR} && ${CMAKE} -E cmake_depends "Unix Makefiles" ${DR_ROOT} ${DR_ROOT}/libutil ${BLD_DIR} ${BLD_DIR}/libutil ${BLD_DIR}/libutil/CMakeFiles/drconfiglib.dir/DependInfo.cmake --color=
#[ 88%] Building C object libutil/CMakeFiles/drconfiglib.dir/dr_config.c.o
cd ${BLD_DIR}/libutil && ${CC}  -DNOT_DYNAMORIO_CORE_PROPER -I${DR_ROOT}/core/unix -I${BLD_DIR} -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/win32 -I${DR_ROOT}/core/lib -I${DR_ROOT}/core  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable      -DRC_IS_DRCONFIGLIB -DNOT_DYNAMORIO_CORE -o CMakeFiles/drconfiglib.dir/dr_config.c.o   -c ${DR_ROOT}/libutil/dr_config.c
#[ 88%] Building C object libutil/CMakeFiles/drconfiglib.dir/utils.c.o
cd ${BLD_DIR}/libutil && ${CC}  -DNOT_DYNAMORIO_CORE_PROPER -I${DR_ROOT}/core/unix -I${BLD_DIR} -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/win32 -I${DR_ROOT}/core/lib -I${DR_ROOT}/core  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable      -DRC_IS_DRCONFIGLIB -DNOT_DYNAMORIO_CORE -o CMakeFiles/drconfiglib.dir/utils.c.o   -c ${DR_ROOT}/libutil/utils.c
#[100%] Building C object libutil/CMakeFiles/drconfiglib.dir/__/core/unix/nudgesig.c.o
cd ${BLD_DIR}/libutil && ${CC}  -DNOT_DYNAMORIO_CORE_PROPER -I${DR_ROOT}/core/unix -I${BLD_DIR} -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/win32 -I${DR_ROOT}/core/lib -I${DR_ROOT}/core  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable      -DRC_IS_DRCONFIGLIB -DNOT_DYNAMORIO_CORE -o CMakeFiles/drconfiglib.dir/__/core/unix/nudgesig.c.o   -c ${DR_ROOT}/core/unix/nudgesig.c
#[100%] Linking C static library ../lib64/libdrconfiglib.a
#cd ${BLD_DIR}/libutil && ${CMAKE} -P CMakeFiles/drconfiglib.dir/cmake_clean_target.cmake
cd ${BLD_DIR}/libutil && ${CMAKE} -E cmake_link_script CMakeFiles/drconfiglib.dir/link.txt --verbose=
#[100%] Built target drconfiglib
#cd ${BLD_DIR} && ${CMAKE} -E cmake_depends "Unix Makefiles" ${DR_ROOT} ${DR_ROOT}/tools ${BLD_DIR} ${BLD_DIR}/tools ${BLD_DIR}/tools/CMakeFiles/drrun.dir/DependInfo.cmake --color=
#[100%] Building C object tools/CMakeFiles/drrun.dir/drdeploy.c.o
cd ${BLD_DIR}/tools && ${CC}  -DNOT_DYNAMORIO_CORE -I${BLD_DIR} -I${DR_ROOT}/libutil -I${DR_ROOT}/core -I${DR_ROOT}/core/lib  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable      -DRC_IS_drrun -DDRRUN -o CMakeFiles/drrun.dir/drdeploy.c.o   -c ${DR_ROOT}/tools/drdeploy.c
#[100%] Linking C executable ../bin64/drrun
cd ${BLD_DIR}/tools && ${CMAKE} -E cmake_link_script CMakeFiles/drrun.dir/link.txt --verbose=
cd ${BLD_DIR}/tools && ${CMAKE} -D lib=${BLD_DIR}/bin64/drrun -D check_textrel=ON -D check_deps=OFF -D check_libc=ON -D READELF_EXECUTABLE=/usr/bin/readelf -P ${DR_ROOT}/core/CMake_readelf.cmake
#[100%] Built target drrun
