BLD_DIR="/home/sgx/project/sgx/sgx-dbi/libdynamorio/debug"
DR_ROOT="/home/sgx/project/sgx/sgx-dbi/libdynamorio"

CMAKE="/usr/bin/cmake"
PERL="/usr/bin/perl"
CPP="/usr/bin/cpp"
CC="/usr/bin/cc"
AS="/usr/bin/as"
#cd ${BLD_DIR} && ${CMAKE} -E cmake_depends "Unix Makefiles" ${DR_ROOT} ${DR_ROOT} ${BLD_DIR} ${BLD_DIR} ${BLD_DIR}/CMakeFiles/api_headers.dir/DependInfo.cmake --color=
#[  0%] Generating include/dr_app.h, include/dr_api.h
#cd ${DR_ROOT}/core && ${PERL} ${DR_ROOT}/core/lib/genapi.pl -core ${DR_ROOT}/core -header ${BLD_DIR}/include "-DINTERNAL -DDEBUG -DDRSTATS_DEMO -DX86 -DX64 -DLINUX -DUNIX -DCLIENT_INTERFACE -DAPP_EXPORTS -DKSTATS -DHAVE_FVISIBILITY -DHAVE_TYPELIMITS_CONTROL -DANNOTATIONS -DDR_DO_NOT_DEFINE_uint -DDR_DO_NOT_DEFINE_ushort -DDR__Bool_EXISTS -DASSEMBLE_WITH_GAS -DHAVE_MEMINFO -DHAVE_MEMINFO_MAPS -DHAVE_TLS -DHAVE_SIGALTSTACK -DUSE_VISIBILITY_ATTRIBUTES -DDYNAMORIO_IR_EXPORTS -DCUSTOM_TRACES -DCLIENT_SIDELINE -DDR_APP_EXPORTS -DDEBUG_MEMORY -DHEAP_ACCOUNTING -DDEADLOCK_AVOIDANCE -DSHARING_STUDY -DHASHTABLE_STATISTICS -DAPI_EXPORT_ONLY"
#[  0%] Built target api_headers
#cd ${BLD_DIR} && ${CMAKE} -E cmake_depends "Unix Makefiles" ${DR_ROOT} ${DR_ROOT}/core ${BLD_DIR} ${BLD_DIR}/core ${BLD_DIR}/core/CMakeFiles/generate_syslog.dir/DependInfo.cmake --color=
#[  0%] Generating ../event_strings.h
#cd ${BLD_DIR}/core && ${PERL} ${DR_ROOT}/core/gen_event_strings.pl ${DR_ROOT}/core/win32/events.mc ${BLD_DIR}/event_strings.h
#[  0%] Built target generate_syslog
#cd ${BLD_DIR} && ${CMAKE} -E cmake_depends "Unix Makefiles" ${DR_ROOT} ${DR_ROOT}/core ${BLD_DIR} ${BLD_DIR}/core ${BLD_DIR}/core/CMakeFiles/drhelper.dir/DependInfo.cmake --color=
#[  0%] Building ASM object core/CMakeFiles/drhelper.dir/arch/asm_shared.asm.o
#cd ${BLD_DIR}/core && ${CPP}  -g   -fPIC -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations   -DCPP2ASM -E ${DR_ROOT}/core/arch/asm_shared.asm -o CMakeFiles/drhelper.dir/arch/asm_shared.asm.o.s
#cd ${BLD_DIR}/core && ${CMAKE} -Dfile=CMakeFiles/drhelper.dir/arch/asm_shared.asm.o.s -P "${DR_ROOT}/make/CMake_asm.cmake"
cd ${BLD_DIR}/core && ${AS}  -mmnemonic=intel -msyntax=intel -mnaked-reg --64 --noexecstack -g -o CMakeFiles/drhelper.dir/arch/asm_shared.asm.o CMakeFiles/drhelper.dir/arch/asm_shared.asm.o.s
#[  0%] Building ASM object core/CMakeFiles/drhelper.dir/arch/x86/x86_shared.asm.o
#cd ${BLD_DIR}/core && ${CPP}  -g   -fPIC -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations   -DCPP2ASM -E ${DR_ROOT}/core/arch/x86/x86_shared.asm -o CMakeFiles/drhelper.dir/arch/x86/x86_shared.asm.o.s
#cd ${BLD_DIR}/core && ${CMAKE} -Dfile=CMakeFiles/drhelper.dir/arch/x86/x86_shared.asm.o.s -P "${DR_ROOT}/make/CMake_asm.cmake"
cd ${BLD_DIR}/core && ${AS}  -mmnemonic=intel -msyntax=intel -mnaked-reg --64 --noexecstack -g -o CMakeFiles/drhelper.dir/arch/x86/x86_shared.asm.o CMakeFiles/drhelper.dir/arch/x86/x86_shared.asm.o.s
#[  0%] Building C object core/CMakeFiles/drhelper.dir/lib/dr_helper.c.o
cd ${BLD_DIR}/core && ${CC}   -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable     -fPIC -o CMakeFiles/drhelper.dir/lib/dr_helper.c.o   -c ${DR_ROOT}/core/lib/dr_helper.c
#[  5%] Linking C static library ../lib64/libdrhelper.a
#cd ${BLD_DIR}/core && ${CMAKE} -P CMakeFiles/drhelper.dir/cmake_clean_target.cmake
cd ${BLD_DIR}/core && ${CMAKE} -E cmake_link_script CMakeFiles/drhelper.dir/link.txt --verbose=
#[  5%] Built target drhelper
#cd ${BLD_DIR} && ${CMAKE} -E cmake_depends "Unix Makefiles" ${DR_ROOT} ${DR_ROOT}/core ${BLD_DIR} ${BLD_DIR}/core ${BLD_DIR}/core/CMakeFiles/dynamorio.dir/DependInfo.cmake --color=
#[  5%] Building C object core/CMakeFiles/dynamorio.dir/options.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/options.c.o   -c ${DR_ROOT}/core/options.c
#[  5%] Building C object core/CMakeFiles/dynamorio.dir/dynamo.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/dynamo.c.o   -c ${DR_ROOT}/core/dynamo.c
#[  5%] Building C object core/CMakeFiles/dynamorio.dir/fragment.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/fragment.c.o   -c ${DR_ROOT}/core/fragment.c
#[ 10%] Building C object core/CMakeFiles/dynamorio.dir/fcache.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/fcache.c.o   -c ${DR_ROOT}/core/fcache.c
#[ 10%] Building C object core/CMakeFiles/dynamorio.dir/link.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/link.c.o   -c ${DR_ROOT}/core/link.c
#[ 10%] Building C object core/CMakeFiles/dynamorio.dir/dispatch.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/dispatch.c.o   -c ${DR_ROOT}/core/dispatch.c
#[ 10%] Building C object core/CMakeFiles/dynamorio.dir/emit.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/emit.c.o   -c ${DR_ROOT}/core/emit.c
#[ 15%] Building C object core/CMakeFiles/dynamorio.dir/utils.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/utils.c.o   -c ${DR_ROOT}/core/utils.c
#[ 15%] Building C object core/CMakeFiles/dynamorio.dir/config.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/config.c.o   -c ${DR_ROOT}/core/config.c
#[ 15%] Building C object core/CMakeFiles/dynamorio.dir/stats.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/stats.c.o   -c ${DR_ROOT}/core/stats.c
#[ 15%] Building C object core/CMakeFiles/dynamorio.dir/heap.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/heap.c.o   -c ${DR_ROOT}/core/heap.c
#[ 15%] Building C object core/CMakeFiles/dynamorio.dir/monitor.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/monitor.c.o   -c ${DR_ROOT}/core/monitor.c
#[ 21%] Building C object core/CMakeFiles/dynamorio.dir/perfctr.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/perfctr.c.o   -c ${DR_ROOT}/core/perfctr.c
#[ 21%] Building C object core/CMakeFiles/dynamorio.dir/vmareas.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/vmareas.c.o   -c ${DR_ROOT}/core/vmareas.c
#[ 21%] Building C object core/CMakeFiles/dynamorio.dir/rct.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/rct.c.o   -c ${DR_ROOT}/core/rct.c
#[ 21%] Building C object core/CMakeFiles/dynamorio.dir/hotpatch.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/hotpatch.c.o   -c ${DR_ROOT}/core/hotpatch.c
#[ 26%] Building C object core/CMakeFiles/dynamorio.dir/hashtable.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/hashtable.c.o   -c ${DR_ROOT}/core/hashtable.c
#[ 26%] Building C object core/CMakeFiles/dynamorio.dir/module_list.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/module_list.c.o   -c ${DR_ROOT}/core/module_list.c
#[ 26%] Building C object core/CMakeFiles/dynamorio.dir/moduledb.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/moduledb.c.o   -c ${DR_ROOT}/core/moduledb.c
#[ 26%] Building C object core/CMakeFiles/dynamorio.dir/perscache.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/perscache.c.o   -c ${DR_ROOT}/core/perscache.c
#[ 31%] Building C object core/CMakeFiles/dynamorio.dir/nudge.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/nudge.c.o   -c ${DR_ROOT}/core/nudge.c
#[ 31%] Building C object core/CMakeFiles/dynamorio.dir/synch.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/synch.c.o   -c ${DR_ROOT}/core/synch.c
#[ 31%] Building C object core/CMakeFiles/dynamorio.dir/buildmark.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/buildmark.c.o   -c ${DR_ROOT}/core/buildmark.c
#[ 31%] Building C object core/CMakeFiles/dynamorio.dir/loader_shared.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/loader_shared.c.o   -c ${DR_ROOT}/core/loader_shared.c
#[ 31%] Building C object core/CMakeFiles/dynamorio.dir/io.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/io.c.o   -c ${DR_ROOT}/core/io.c
#[ 36%] Building C object core/CMakeFiles/dynamorio.dir/native_exec.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/native_exec.c.o   -c ${DR_ROOT}/core/native_exec.c
#[ 36%] Building C object core/CMakeFiles/dynamorio.dir/lib/instrument.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/lib/instrument.c.o   -c ${DR_ROOT}/core/lib/instrument.c
#[ 36%] Building C object core/CMakeFiles/dynamorio.dir/translate.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/translate.c.o   -c ${DR_ROOT}/core/translate.c
#[ 36%] Building C object core/CMakeFiles/dynamorio.dir/annotations.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/annotations.c.o   -c ${DR_ROOT}/core/annotations.c
#[ 42%] Building C object core/CMakeFiles/dynamorio.dir/jit_opt.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/jit_opt.c.o   -c ${DR_ROOT}/core/jit_opt.c
#[ 42%] Building C object core/CMakeFiles/dynamorio.dir/string.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/string.c.o   -c ${DR_ROOT}/core/string.c
#[ 42%] Building C object core/CMakeFiles/dynamorio.dir/__/third_party/libgcc/udivmoddi4.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/__/third_party/libgcc/udivmoddi4.c.o   -c ${DR_ROOT}/third_party/libgcc/udivmoddi4.c
#[ 42%] Building C object core/CMakeFiles/dynamorio.dir/arch/arch.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/arch/arch.c.o   -c ${DR_ROOT}/core/arch/arch.c
#[ 42%] Building C object core/CMakeFiles/dynamorio.dir/arch/emit_utils_shared.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/arch/emit_utils_shared.c.o   -c ${DR_ROOT}/core/arch/emit_utils_shared.c
#[ 47%] Building C object core/CMakeFiles/dynamorio.dir/arch/x86/emit_utils.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/arch/x86/emit_utils.c.o   -c ${DR_ROOT}/core/arch/x86/emit_utils.c
#[ 47%] Building C object core/CMakeFiles/dynamorio.dir/arch/opnd_shared.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/arch/opnd_shared.c.o   -c ${DR_ROOT}/core/arch/opnd_shared.c
#[ 47%] Building C object core/CMakeFiles/dynamorio.dir/arch/x86/opnd.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/arch/x86/opnd.c.o   -c ${DR_ROOT}/core/arch/x86/opnd.c
#[ 47%] Building C object core/CMakeFiles/dynamorio.dir/arch/instr_shared.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/arch/instr_shared.c.o   -c ${DR_ROOT}/core/arch/instr_shared.c
#[ 52%] Building C object core/CMakeFiles/dynamorio.dir/arch/x86/instr.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/arch/x86/instr.c.o   -c ${DR_ROOT}/core/arch/x86/instr.c
#[ 52%] Building C object core/CMakeFiles/dynamorio.dir/arch/instrlist.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/arch/instrlist.c.o   -c ${DR_ROOT}/core/arch/instrlist.c
#[ 52%] Building C object core/CMakeFiles/dynamorio.dir/arch/decode_shared.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/arch/decode_shared.c.o   -c ${DR_ROOT}/core/arch/decode_shared.c
#[ 52%] Building C object core/CMakeFiles/dynamorio.dir/arch/x86/decode.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/arch/x86/decode.c.o   -c ${DR_ROOT}/core/arch/x86/decode.c
#[ 57%] Building C object core/CMakeFiles/dynamorio.dir/arch/encode_shared.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/arch/encode_shared.c.o   -c ${DR_ROOT}/core/arch/encode_shared.c
#[ 57%] Building C object core/CMakeFiles/dynamorio.dir/arch/x86/encode.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/arch/x86/encode.c.o   -c ${DR_ROOT}/core/arch/x86/encode.c
#[ 57%] Building C object core/CMakeFiles/dynamorio.dir/arch/disassemble_shared.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/arch/disassemble_shared.c.o   -c ${DR_ROOT}/core/arch/disassemble_shared.c
#[ 57%] Building C object core/CMakeFiles/dynamorio.dir/arch/x86/disassemble.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/arch/x86/disassemble.c.o   -c ${DR_ROOT}/core/arch/x86/disassemble.c
#[ 57%] Building C object core/CMakeFiles/dynamorio.dir/arch/x86/decode_table.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/arch/x86/decode_table.c.o   -c ${DR_ROOT}/core/arch/x86/decode_table.c
#[ 63%] Building C object core/CMakeFiles/dynamorio.dir/arch/x86/decode_fast.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/arch/x86/decode_fast.c.o   -c ${DR_ROOT}/core/arch/x86/decode_fast.c
#[ 63%] Building C object core/CMakeFiles/dynamorio.dir/arch/interp.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/arch/interp.c.o   -c ${DR_ROOT}/core/arch/interp.c
#[ 63%] Building C object core/CMakeFiles/dynamorio.dir/arch/proc_shared.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/arch/proc_shared.c.o   -c ${DR_ROOT}/core/arch/proc_shared.c
#[ 63%] Building C object core/CMakeFiles/dynamorio.dir/arch/x86/proc.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/arch/x86/proc.c.o   -c ${DR_ROOT}/core/arch/x86/proc.c
#[ 68%] Building C object core/CMakeFiles/dynamorio.dir/arch/mangle_shared.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/arch/mangle_shared.c.o   -c ${DR_ROOT}/core/arch/mangle_shared.c
#[ 68%] Building C object core/CMakeFiles/dynamorio.dir/arch/x86/mangle.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/arch/x86/mangle.c.o   -c ${DR_ROOT}/core/arch/x86/mangle.c
#[ 68%] Building C object core/CMakeFiles/dynamorio.dir/arch/clean_call_opt_shared.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/arch/clean_call_opt_shared.c.o   -c ${DR_ROOT}/core/arch/clean_call_opt_shared.c
#[ 68%] Building C object core/CMakeFiles/dynamorio.dir/arch/x86/clean_call_opt.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/arch/x86/clean_call_opt.c.o   -c ${DR_ROOT}/core/arch/x86/clean_call_opt.c
#[ 68%] Building C object core/CMakeFiles/dynamorio.dir/arch/steal_reg.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/arch/steal_reg.c.o   -c ${DR_ROOT}/core/arch/steal_reg.c
#[ 73%] Building C object core/CMakeFiles/dynamorio.dir/arch/x86_code.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/arch/x86_code.c.o   -c ${DR_ROOT}/core/arch/x86_code.c
#[ 73%] Building ASM object core/CMakeFiles/dynamorio.dir/arch/x86/x86.asm.o
#cd ${BLD_DIR}/core && ${CPP}  -g -fPIC   -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -Ddynamorio_EXPORTS -DCPP2ASM -E ${DR_ROOT}/core/arch/x86/x86.asm -o CMakeFiles/dynamorio.dir/arch/x86/x86.asm.o.s
#cd ${BLD_DIR}/core && ${CMAKE} -Dfile=CMakeFiles/dynamorio.dir/arch/x86/x86.asm.o.s -P "${DR_ROOT}/make/CMake_asm.cmake"
cd ${BLD_DIR}/core && ${AS}  -mmnemonic=intel -msyntax=intel -mnaked-reg --64 --noexecstack -g -o CMakeFiles/dynamorio.dir/arch/x86/x86.asm.o CMakeFiles/dynamorio.dir/arch/x86/x86.asm.o.s
#[ 73%] Building C object core/CMakeFiles/dynamorio.dir/arch/x86/optimize.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/arch/x86/optimize.c.o   -c ${DR_ROOT}/core/arch/x86/optimize.c
#[ 73%] Building C object core/CMakeFiles/dynamorio.dir/arch/sideline.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/arch/sideline.c.o   -c ${DR_ROOT}/core/arch/sideline.c
#[ 78%] Building C object core/CMakeFiles/dynamorio.dir/arch/retcheck.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/arch/retcheck.c.o   -c ${DR_ROOT}/core/arch/retcheck.c
#[ 78%] Building C object core/CMakeFiles/dynamorio.dir/arch/x86/x86_to_x64.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/arch/x86/x86_to_x64.c.o   -c ${DR_ROOT}/core/arch/x86/x86_to_x64.c
#[ 78%] Building C object core/CMakeFiles/dynamorio.dir/unix/os.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/unix/os.c.o   -c ${DR_ROOT}/core/unix/os.c
#[ 78%] Building C object core/CMakeFiles/dynamorio.dir/unix/signal.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/unix/signal.c.o   -c ${DR_ROOT}/core/unix/signal.c
#[ 84%] Building C object core/CMakeFiles/dynamorio.dir/unix/module.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/unix/module.c.o   -c ${DR_ROOT}/core/unix/module.c
#[ 84%] Building C object core/CMakeFiles/dynamorio.dir/unix/pcprofile.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/unix/pcprofile.c.o   -c ${DR_ROOT}/core/unix/pcprofile.c
#[ 84%] Building C object core/CMakeFiles/dynamorio.dir/unix/stackdump.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/unix/stackdump.c.o   -c ${DR_ROOT}/core/unix/stackdump.c
#[ 84%] Building C object core/CMakeFiles/dynamorio.dir/unix/diagnost.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/unix/diagnost.c.o   -c ${DR_ROOT}/core/unix/diagnost.c
#[ 84%] Building C object core/CMakeFiles/dynamorio.dir/unix/loader.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/unix/loader.c.o   -c ${DR_ROOT}/core/unix/loader.c
#[ 89%] Building C object core/CMakeFiles/dynamorio.dir/unix/loader_linux.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/unix/loader_linux.c.o   -c ${DR_ROOT}/core/unix/loader_linux.c
#[ 89%] Building C object core/CMakeFiles/dynamorio.dir/unix/memquery_linux.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/unix/memquery_linux.c.o   -c ${DR_ROOT}/core/unix/memquery_linux.c
#[ 89%] Building C object core/CMakeFiles/dynamorio.dir/unix/memquery.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/unix/memquery.c.o   -c ${DR_ROOT}/core/unix/memquery.c
#[ 89%] Building C object core/CMakeFiles/dynamorio.dir/unix/memcache.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/unix/memcache.c.o   -c ${DR_ROOT}/core/unix/memcache.c
#[ 94%] Building C object core/CMakeFiles/dynamorio.dir/unix/module_elf.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/unix/module_elf.c.o   -c ${DR_ROOT}/core/unix/module_elf.c
#[ 94%] Building C object core/CMakeFiles/dynamorio.dir/unix/ksynch_linux.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/unix/ksynch_linux.c.o   -c ${DR_ROOT}/core/unix/ksynch_linux.c
#[ 94%] Building C object core/CMakeFiles/dynamorio.dir/unix/tls_linux_x86.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/unix/tls_linux_x86.c.o   -c ${DR_ROOT}/core/unix/tls_linux_x86.c
#[ 94%] Building C object core/CMakeFiles/dynamorio.dir/unix/signal_linux.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/unix/signal_linux.c.o   -c ${DR_ROOT}/core/unix/signal_linux.c
#[100%] Building C object core/CMakeFiles/dynamorio.dir/unix/signal_linux_x86.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/unix/signal_linux_x86.c.o   -c ${DR_ROOT}/core/unix/signal_linux_x86.c
#[100%] Building C object core/CMakeFiles/dynamorio.dir/unix/native_elf.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/unix/native_elf.c.o   -c ${DR_ROOT}/core/unix/native_elf.c
#[100%] Building C object core/CMakeFiles/dynamorio.dir/unix/nudgesig.c.o
cd ${BLD_DIR}/core && ${CC}  -Ddynamorio_EXPORTS -I${DR_ROOT}/core/arch/x86 -I${DR_ROOT}/core/unix -I${DR_ROOT}/core/arch -I${DR_ROOT}/core/lib -I${BLD_DIR} -I${BLD_DIR}/include/annotations  -m64  -fno-strict-aliasing -fno-stack-protector -fvisibility=internal  -std=gnu99 -ggdb3 -fno-omit-frame-pointer -fno-builtin-strcmp -Wall -Werror -Wwrite-strings -Wno-unused-but-set-variable   -fPIC   -o CMakeFiles/dynamorio.dir/unix/nudgesig.c.o   -c ${DR_ROOT}/core/unix/nudgesig.c
#[100%] Linking C shared library ../lib64/debug/libdynamorio.so
#cd ${BLD_DIR}/core && ${CMAKE} -D outfile=${BLD_DIR}/core/dynamorio.ldscript -DCMAKE_LINKER=/usr/bin/ld -DCMAKE_COMPILER_IS_GNUCC=TRUE -DLD_FLAGS=-melf_x86_64 -Dset_preferred=1 -Dreplace_maxpagesize= -Dpreferred_base=0x71000000 -Dadd_bounds_vars=ON -P ${DR_ROOT}/make/ldscript.cmake
cd ${BLD_DIR}/core && ${CMAKE} -E cmake_link_script CMakeFiles/dynamorio.dir/link.txt --verbose=
cd ${BLD_DIR}/core && ${CMAKE} -D lib=${BLD_DIR}/lib64/debug/libdynamorio.so -D check_textrel=ON -D check_deps=ON -D check_libc=OFF -D check_interp=ON -D READELF_EXECUTABLE=/usr/bin/readelf -P ${DR_ROOT}/core/CMake_readelf.cmake
#[100%] Built target dynamorio
