#ifndef _ST_SIZE_H__
#define _ST_SIZE_H__

#define len_sigevent 64
#define len_siginfo 128
#define len_sockaddr 16
#define len_stat 144
#define len_statfs 120
#define len___sysctl_args 80
#define len_sysinfo 112
#define len_task_struct 6848
#define len_timespec 16
#define len_timeval 16
#define len_timex 208
#define len_timezone 8
#define len_ustat 32
#define len_utimbuf 16
#define len_timespec 16
#define len_timer_t 4
#define len_time_t 8
#define len_u32 4
#define len_u64 8
#define len_uid_t 4
#define len_union_semun 8
#define len_unsigned 4
#define len_unsigned_char 1
#define len_unsigned_int 4
#define len_unsigned_long 8
#define len_aio_context_t 8
#define len_cap_user_data_t 8
#define len_cap_user_header_t 8
#define len_clockid_t 4
#define len_fd_set 128
#define len_gid_t 4
#define len_int 4
#define len_key_serial_t 4
#define len_key_t 4
#define len_loff_t 8
#define len_long 8
#define len_mode_t 4
#define len_mqd_t 4
#define len_off_t 8
#define len_pid_t 4
#define len_siginfo_t 128
#define len_kernel_sigset 8
#define len_size_t 8
#define len_stack_t 24
#define len_epoll_event 16
#define len_file_handle 8
#define len_getcpu_cache 128
#define len_iocb 64
#define len_io_event 32
#define len_iovec 16
#define len_itimerspec 32
#define len_itimerval 32
#define len_kexec_segment 32
#define len_linux_dirent 24
#define len_linux_dirent64 24
#define len_mmsghdr 64
#define len_mq_attr 32
#define len_msgbuf 16
#define len_msghdr 88
#define len_msqid_ds 104
#define len_utsname 390
#define len_perf_event_attr 112
#define len_pollfd 8
#define len_pollfd 8
#define len_pt_regs 168
#define len_rlimit 16
#define len_rlimit64 16
#define len_robust_list_head 24
#define len_rusage 144
#define len_sched_param 4
#define len_sembuf 6
#define len_shmid_ds 88
#define len_kernel_sigaction 32
#define len_sigaction 152
#define len_sigevent 64
#define len_siginfo 128
#define len_sockaddr 16
#define len_stat 144
#define len_statfs 120
#define len___sysctl_args 80
#define len_sysinfo 112
#define len_task_struct 6848
#define len_timespec 16
#define len_timeval 16
#define len_timex 208
#define len_timezone 8
#define len_ustat 32
#define len_utimbuf 16
#define len_timespec 16
#define len_timer_t 4
#define len_time_t 8
#define len_u32 4
#define len_u64 8
#define len_uid_t 4
#define len_union_semun 8
#define len_unsigned 4
#define len_unsigned_char 1
#define len_unsigned_int 4
#define len_unsigned_long 8

#endif  //#define _ST_SIZE_H__
